"""empty message

Revision ID: 4357869ceb77
Revises: 4254519e8246
Create Date: 2024-08-05 18:42:37.577832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4357869ceb77'
down_revision: Union[str, None] = '4254519e8246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('conversation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversation', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('conversation_message', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('conversation_message', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversation_message', 'is_assistant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('conversation_message', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('conversation_message', 'workflow_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_message', 'workflow_results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('conversation_message', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('conversation_message', 'is_assistant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('conversation_message', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversation_message', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('conversation_message', 'created_at')
    op.alter_column('conversation', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('conversation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('conversation', 'created_at')
    # ### end Alembic commands ###
